// angular-ui/src/app/app.component.ts
import { ChangeDetectionStrategy, Component, computed, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { UserService } from "./user.service";
import { User, UserCreate } from "./user.model";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="container">
      <header>
        <h1>User App</h1>
        <p>Basic CRUD operations</p>
      </header>

      <section class="card">
        <h2>{{ editingId() === null ? "Create User" : "Edit User" }}</h2>
        <div class="grid">
          <label>
            Name
            <input
              [ngModel]="formName()"
              (ngModelChange)="formName.set($event)"
              placeholder="Jane Doe"
            />
          </label>
          <label>
            Email
            <input
              [ngModel]="formEmail()"
              (ngModelChange)="formEmail.set($event)"
              placeholder="jane@example.com"
              type="email"
            />
          </label>
          <label>
            Age
            <input
              [ngModel]="formAge()"
              (ngModelChange)="formAge.set($event === '' ? null : Number($event))"
              placeholder="30"
              type="number"
              min="0"
            />
          </label>
        </div>
        <div class="actions">
          <button [disabled]="!canSubmit()" (click)="submit()">
            {{ editingId() === null ? "Create" : "Update" }}
          </button>
          <button class="secondary" *ngIf="editingId() !== null" (click)="resetForm()">
            Cancel
          </button>
        </div>
        <p class="error" *ngIf="error()">{{ error() }}</p>
      </section>

      <section class="card">
        <h2>Users</h2>
        <p *ngIf="loading()">Loading...</p>
        <p *ngIf="!loading() && users().length === 0">No users yet</p>
        <ul class="list" *ngIf="users().length > 0">
          <li *ngFor="let user of users(); trackBy: trackById">
            <div>
              <strong>{{ user.name }}</strong>
              <div class="muted">{{ user.email }}</div>
              <div class="muted">Age: {{ user.age ?? "-" }}</div>
            </div>
            <div class="actions">
              <button class="secondary" (click)="edit(user)">Edit</button>
              <button class="danger" (click)="remove(user.id)">Delete</button>
            </div>
          </li>
        </ul>
      </section>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent {
  private readonly emptyForm: UserCreate = { name: "", email: "", age: null };

  readonly users = signal<User[]>([]);
  readonly formName = signal(this.emptyForm.name);
  readonly formEmail = signal(this.emptyForm.email);
  readonly formAge = signal<number | null>(this.emptyForm.age);
  readonly editingId = signal<number | null>(null);
  readonly error = signal<string | null>(null);
  readonly loading = signal(false);

  readonly canSubmit = computed(
    () => this.formName().trim().length >= 2 && this.formEmail().includes("@")
  );

  constructor(private userService: UserService) {
    this.loadUsers();
  }

  trackById(_: number, user: User) {
    return user.id;
  }

  loadUsers() {
    this.loading.set(true);
    this.userService.listUsers().subscribe({
      next: (data) => this.users.set(data),
      error: (err) => this.error.set(err.message ?? "Failed to load"),
      complete: () => this.loading.set(false)
    });
  }

  submit() {
    this.error.set(null);
    const payload: UserCreate = {
      name: this.formName(),
      email: this.formEmail(),
      age: this.formAge()
    };
    if (this.editingId() === null) {
      this.userService.createUser(payload).subscribe({
        next: (created) => this.users.update((list) => [...list, created]),
        error: (err) => this.error.set(err.message ?? "Failed to create"),
        complete: () => this.resetForm()
      });
      return;
    }

    this.userService.updateUser(this.editingId()!, payload).subscribe({
      next: (updated) =>
        this.users.update((list) => list.map((u) => (u.id === updated.id ? updated : u))),
      error: (err) => this.error.set(err.message ?? "Failed to update"),
      complete: () => this.resetForm()
    });
  }

  edit(user: User) {
    this.editingId.set(user.id);
    this.formName.set(user.name);
    this.formEmail.set(user.email);
    this.formAge.set(user.age);
  }

  remove(id: number) {
    this.error.set(null);
    this.userService.deleteUser(id).subscribe({
      next: () => this.users.update((list) => list.filter((u) => u.id !== id)),
      error: (err) => this.error.set(err.message ?? "Failed to delete")
    });
  }

  resetForm() {
    this.formName.set(this.emptyForm.name);
    this.formEmail.set(this.emptyForm.email);
    this.formAge.set(this.emptyForm.age);
    this.editingId.set(null);
  }
}

// react-ui/src/App.tsx
import { useEffect, useMemo, useState } from "react";
import { api } from "./api";
import type { User, UserCreate } from "./types";

const emptyForm: UserCreate = { name: "", email: "", age: null };

export default function App() {
  const [users, setUsers] = useState<User[]>([]);
  const [form, setForm] = useState<UserCreate>(emptyForm);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const canSubmit = useMemo(
    () => form.name.trim().length >= 2 && form.email.includes("@"),
    [form]
  );

  useEffect(() => {
    setLoading(true);
    api
      .listUsers()
      .then(setUsers)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  const resetForm = () => {
    setForm(emptyForm);
    setEditingId(null);
  };

  const handleSubmit = async () => {
    setError(null);
    try {
      if (editingId === null) {
        const created = await api.createUser(form);
        setUsers((prev) => [...prev, created]);
      } else {
        const updated = await api.updateUser(editingId, form);
        setUsers((prev) => prev.map((u) => (u.id === updated.id ? updated : u)));
      }
      resetForm();
    } catch (err) {
      setError((err as Error).message);
    }
  };

  const handleEdit = (user: User) => {
    setEditingId(user.id);
    setForm({ name: user.name, email: user.email, age: user.age });
  };

  const handleDelete = async (id: number) => {
    setError(null);
    try {
      await api.deleteUser(id);
      setUsers((prev) => prev.filter((u) => u.id !== id));
    } catch (err) {
      setError((err as Error).message);
    }
  };

  return (
    <div className="container">
      <header>
        <h1>User App</h1>
        <p>Basic CRUD operations</p>
      </header>

      <section className="card">
        <h2>{editingId === null ? "Create User" : "Edit User"}</h2>
        <div className="grid">
          <label>
            Name
            <input
              value={form.name}
              onChange={(e) => setForm({ ...form, name: e.target.value })}
              placeholder="Jane Doe"
            />
          </label>
          <label>
            Email
            <input
              value={form.email}
              onChange={(e) => setForm({ ...form, email: e.target.value })}
              placeholder="jane@example.com"
              type="email"
            />
          </label>
          <label>
            Age
            <input
              value={form.age ?? ""}
              onChange={(e) =>
                setForm({
                  ...form,
                  age: e.target.value ? Number(e.target.value) : null
                })
              }
              placeholder="30"
              type="number"
              min={0}
            />
          </label>
        </div>
        <div className="actions">
          <button disabled={!canSubmit} onClick={handleSubmit}>
            {editingId === null ? "Create" : "Update"}
          </button>
          {editingId !== null && (
            <button className="secondary" onClick={resetForm}>
              Cancel
            </button>
          )}
        </div>
        {error && <p className="error">{error}</p>}
      </section>

      <section className="card">
        <h2>Users</h2>
        {loading ? (
          <p>Loading...</p>
        ) : users.length === 0 ? (
          <p>No users yet</p>
        ) : (
          <ul className="list">
            {users.map((user) => (
              <li key={user.id}>
                <div>
                  <strong>{user.name}</strong>
                  <div className="muted">{user.email}</div>
                  <div className="muted">Age: {user.age ?? "-"}</div>
                </div>
                <div className="actions">
                  <button className="secondary" onClick={() => handleEdit(user)}>
                    Edit
                  </button>
                  <button className="danger" onClick={() => handleDelete(user.id)}>
                    Delete
                  </button>
                </div>
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}
